# Generated by Django 4.0 on 2022-06-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
