# Generated by Django 4.0 on 2022-06-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_itemmodel_name_expireditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ExpiredItems',
        ),
    ]
