# Generated by Django 4.0 on 2022-06-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='name',
            new_name='product',
        ),
    ]
